### ISSUE TITLE
Item Y coordinate -- possible value range conflict with stash page size

### ISSUE THREAD

**Issue by oaken-source** [squeek502/d2itemreader#9]
the D2 item format as described here:
https://squeek502.github.io/d2itemreader/formats/d2.html#item-list-data-format

reserves a 4 bit wide value (possible values range from 0 to 15) for the X coordinate, and a 3 bit wide value (possible values range from 0 to 7) for the Y coordinate. This representation is not sufficient to place the item in the PlugY stash, which has a page size of 10 by 10.

Conveniently, after the Y coordinate is a bit labeled unknown. After checking my limited set of test data, it seems to me that PlugY uses this unknown bit to extend the Y coordinate to a 4 bit field.

It seems tempting to assume that the item format reserves 4 bit for each X and Y coordinate, or are there test files that contradict this assumption?

**Comment by squeek502** [comment]
Sounds reasonable, you're probably right. I'll look into it more; there might be something in the PlugY source that is useful as well.

**Comment by squeek502** [comment]
So I think this 3/4-bit variance is actually vanilla D2 behavior that depends on the `gridY` value in `Inventory.txt`.

- PlugY injects its modified stash size [here](https://github.com/ChaosMarc/PlugY/blob/64792db947bafeadb9dd9ead8827eefbb07a48bf/PlugY/BigStash.cpp#L17-L58) by modifying the compiled `Inventory.txt` values directly, but doesn't change anything else related to the Y coordinate of saved items.
- If you change `Inventory.txt` to use a `gridY` of 10 and use `-direct -txt`, Diablo II will start saving Y values using the 4th bit. Very strange behavior to vary the bit width depending on the max value if you're just going to use a padding bit when writing the 3-bit value anyway, but that seems to be what's going on AFAICT

So, in order to be compatible with [mods like this](https://www.moddb.com/games/diablo-2-lod/addons/10x10-stash-mod-lod-113d-compatible) we'll need to know the contents of `Inventory.txt` while reading items, and then when reading PlugY stash items we just need to tell the reader that `gridY` is actually 10 so we read the Y pos as a 4-bit value.

Very good catch, thank you for creating the issue!

Some more stuff:
- [PlugY stash organizer that reads Y pos as 4 bits](https://github.com/mrpara/d2_plugy_stash_organizer/blob/20ce7f3206a6a4f6f63ac4e921231e90b83d9088/item.py#L34-L36)
- [Another PlugY stash organizer that reads Y pos as 4 bits](https://github.com/youdz/d2-stash-organizer/blob/30f44a25d07f88c0baf49c02bb9e8719b1dbe629/src/scripts/items/parsing/parseSimple.ts#L23-L24)

**Comment by squeek502** [comment]
Actually, I overthought it. The fix is as simple as unconditionally reading the 4-bit value, since the bit ordering means that 1 would be `1000`, and 9 would be `1001` (i.e. the 'unknown' bit is only set if the actual value is large enough to warrant it, which explains why it was labeled 'unknown' by people only looking at vanilla D2 saves since it would never be non-zero without `Inventory.txt` changes).

Will fix the library and docs.
